GRANT SELECT, INSERT, UPDATE, DELETE ON public.notes TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.note_versions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tasks TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.habits TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.habit_logs TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.habit_certificates TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.habit_sections TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.folders TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lists TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sections TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.countdowns TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_settings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.subscription_status TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.file_attachments TO authenticated;

GRANT ALL ON public.notes TO service_role;
GRANT ALL ON public.note_versions TO service_role;
GRANT ALL ON public.tasks TO service_role;
GRANT ALL ON public.habits TO service_role;
GRANT ALL ON public.habit_logs TO service_role;
GRANT ALL ON public.habit_certificates TO service_role;
GRANT ALL ON public.habit_sections TO service_role;
GRANT ALL ON public.folders TO service_role;
GRANT ALL ON public.lists TO service_role;
GRANT ALL ON public.sections TO service_role;
GRANT ALL ON public.countdowns TO service_role;
GRANT ALL ON public.user_settings TO service_role;
GRANT ALL ON public.subscription_status TO service_role;
GRANT ALL ON public.file_attachments TO service_role;